[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "Dodo_Robot_Sim2Real"
author = "Shanshan Zhang"
maintainer = "Shanshan Zhang"
description="Sim-to-Real Locomotion tasks by using Isaaclab and Isaacsim for our customized dodo bipedal robot in TUM MIRMI Lab."
repository = "https://github.com/splendidsummer/Dodo_Robot_Sim2Real.git"
keywords = ["sim-to-real", "isaaclab", "bipedal", "locomotion", "dodorobot", "customize"]

[dependencies]
"omni.isaac.lab" = {}
"omni.isaac.lab_assets" = {}
"omni.isaac.lab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "dodo_bipedal_locomotion"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
